apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets-workloads
  namespace: workloads
  labels:
    zero-trust: "true"
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    clientID: "WORKLOAD_IDENTITY_CLIENT_ID"
    keyvaultName: "KEY_VAULT_NAME"
    tenantId: "AZURE_TENANT_ID"
    objects: |
      array:
        - |
          objectName: db-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: api-key
          objectType: secret
          objectVersion: ""
