apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets-workloads
  namespace: workloads
spec:
  parameters:
    clientID: "REPLACE_WITH_WORKLOAD_IDENTITY_CLIENT_ID"
    keyvaultName: "REPLACE_WITH_KEY_VAULT_NAME"
    tenantId: "REPLACE_WITH_AZURE_TENANT_ID"
