apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:admin, applications, *, * *, allow
    p, role:admin, applications, *, * /, allow
    p, role:admin, clusters, *, * *, allow
    p, role:admin, repositories, *, * *, allow
    p, role:admin, projects, *, * *, allow
    p, role:admin, accounts, *, * *, allow
    p, role:admin, gpgkeys, *, * *, allow
    g, /:Admin, role:admin
