apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform-outputs-prod
  namespace: workloads
  labels:
    app: zero-trust
    environment: prod
    managed-by: terraform
data:
  ACR_LOGIN: "$ACR_LOGIN"
  KV_NAME: "$KV_NAME"
  CLIENT_ID: "$CLIENT_ID"  # NOT_CONFIGURED (workload identity disabled)
  TENANT_ID: "$TENANT_ID"
  ENVIRONMENT: "prod"