apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets-workloads
  namespace: workloads
spec:
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    clientID: "WORKLOAD_IDENTITY_CLIENT_ID"
    keyvaultName: "KEY_VAULT_NAME"
    tenantId: "AZURE_TENANT_ID"
